export default {
  ITEM_SPAWN_RATE: .2,

  TILE_SIZE: 64,

  PLAYER_SPEED: 320,

  NORMALTOWER_RADIUS: 300,
  ICETOWER_RADIUS: 200,
  FIRETOWER_RADIUS: 300,
  FREEZETOWER_RADIUS: 100,
  LIGHTNINGTOWER_RADIUS: 100,

  NORMALTOWER_COOLDOWN: 300,
  ICETOWER_COOLDOWN: 200,
  FIRETOWER_COOLDOWN: 300,
  FREEZETOWER_COOLDOWN: 100,
  LIGHTNINGTOWER_COOLDOWN: 100,

  NORMAL_PROJECTILE_SPEED: 30,
  ICE_PROJECTILE_SPEED: 20,
  FIRE_PROJECTILE_SPEED: 30,
  FREEZE_PROJECTILE_SPEED: 10,
  LIGHTNING_PROJECTILE_SPEED: 10,
}
