export default {
  ITEM_SPAWN_RATE: .2,
  ITEM_MAX_DISTANCE: 31,
  ITEM_SPAWN_RATE: .05,

  PROJECTILE_SIZE: 10,
  TILE_SIZE: 64,

  ENEMY_MAX_DISTANCE: 48,
  ENEMY_LIVES: 20,
  ENEMY_SPECIAL_RATE: .5,
  ENEMY_SPEED: 50,

  PLAYER_LIVES: 30,
  PLAYER_SPEED: 300,

  BOOST_DURATION: 70,
}
